/**
 * Sidebar Component
 * 
 * Provides controls for:
 * - Displaying and copying your Socket ID
 * - Entering another user's ID to call
 * - Initiating and ending calls
 * 
 * EDUCATIONAL NOTES:
 * - Socket ID is your unique identifier on the signaling server
 * - You need someone else's Socket ID to call them
 * - The ID is automatically generated by Socket.IO when you connect
 */

import React, { useState, useContext, useEffect } from 'react';
import { Button, TextField, Grid, Typography, Container, Paper, Snackbar, Alert, Box, Chip } from '@mui/material';
import { styled } from '@mui/system';
import { Assignment, Phone, PhoneDisabled, Info } from '@mui/icons-material';

import { SocketContext } from '../../context/Context';

const StyledForm = styled('form')({
  display: 'flex',
  flexDirection: 'column',
});

const StyledGridContainer = styled(Grid)(({ theme }) => ({
  width: '100%',
  [theme.breakpoints.down('xs')]: {
    flexDirection: 'column',
  },
  [theme.breakpoints.up('md')]: {
    flexDirection: 'row', // Align elements horizontally for md and up breakpoints
  },
}));

const StyledGridItem = styled(Grid)(({ theme }) => ({
  padding: 20,
}));

const StyledButton = styled(Button)(({ theme }) => ({
  marginTop: 20,
}));

const Sidebar = ({ children }) => {
  const { me, callAccepted, name, setName, callEnded, leaveCall, callUser } = useContext(SocketContext);
  const [idToCall, setIdToCall] = useState('');
  const [showCopySnackBar, setShowCopySnackBar] = useState(false);
  const [warningMessage, setWarningMessage] = useState({
    message: '',
    open: false,
  });

  useEffect(() => {
    // Set default name (can be changed by user)
    const defaultName = "User";
    if (!name) {
      setName(defaultName);
    }
  }, [name, setName]);

  /**
   * Handle paste event - automatically paste Socket ID when field is focused
   * Socket.IO IDs are typically 20 characters long
   */
  const onPasteIdToCall = (event) => {
    event.preventDefault();
    navigator.clipboard.readText().then(text => {
      const trimmedText = text.trim();
      // Socket.IO IDs are typically 20 characters, but we'll accept any reasonable length
      if (trimmedText.length >= 10 && trimmedText.length <= 30) {
        setIdToCall(trimmedText);
        setWarningMessage({ open: false, message: '' });
      } else {
        setWarningMessage({ open: true, message: 'Invalid ID format. Please paste a valid Socket ID.' });
        setIdToCall('');
      }
    }).catch(err => {
      console.error("[SIDEBAR] Failed to read clipboard content:", err);
      setWarningMessage({ open: true, message: 'Could not read clipboard. Please paste manually.' });
    });
  };

  /**
   * Handle call initiation
   */
  const handleCall = () => {
    if (!idToCall || idToCall.trim() === '') {
      setWarningMessage({ open: true, message: 'Please enter a user ID to call' });
      return;
    }

    if (idToCall === me) {
      setWarningMessage({ open: true, message: 'You cannot call yourself!' });
      return;
    }

    console.log('[SIDEBAR] Initiating call to:', idToCall);
    callUser(idToCall);
  };

  /**
   * Handle copying Socket ID to clipboard
   * Uses native Clipboard API with fallback for older browsers
   */
  const handleCopyId = async () => {
    if (!me || me.trim() === '') {
      console.warn('[SIDEBAR] Cannot copy: Socket ID not available yet');
      setWarningMessage({ 
        open: true, 
        message: 'Socket ID not available yet. Please wait for connection...' 
      });
      return;
    }

    try {
      // Try using the modern Clipboard API first
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(me);
        console.log('[SIDEBAR] ✅ Socket ID copied to clipboard:', me);
        setShowCopySnackBar(true);
      } else {
        // Fallback for older browsers
        const textArea = document.createElement('textarea');
        textArea.value = me;
        textArea.style.position = 'fixed';
        textArea.style.left = '-999999px';
        textArea.style.top = '-999999px';
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        
        try {
          const successful = document.execCommand('copy');
          if (successful) {
            console.log('[SIDEBAR] ✅ Socket ID copied to clipboard (fallback):', me);
            setShowCopySnackBar(true);
          } else {
            throw new Error('Copy command failed');
          }
        } catch (err) {
          throw new Error('Fallback copy failed');
        } finally {
          document.body.removeChild(textArea);
        }
      }
    } catch (error) {
      console.error('[SIDEBAR] ❌ Failed to copy Socket ID:', error);
      setWarningMessage({ 
        open: true, 
        message: 'Failed to copy ID. Please copy manually: ' + me 
      });
    }
  };

  return (
    <Container>
      <Paper elevation={10}>
        <StyledForm noValidate autoComplete="off">
          <StyledGridContainer container alignItems="flex-start"> {/* Align items at the top */}
            <StyledGridItem item xs={12} md={6}>
              <Typography gutterBottom variant="h6">Account Info</Typography>
              <TextField label="Name" value={name}  onChange={(e) => setName(e.target.value)} fullWidth disabled/>
              {me && (
                <Typography variant="caption" color="text.secondary" sx={{ mt: 1, mb: 0.5, display: 'block' }}>
                  Your ID: {me}
                </Typography>
              )}
              <StyledButton 
                variant="contained" 
                color="primary" 
                fullWidth 
                startIcon={<Assignment fontSize="large" />}
                onClick={handleCopyId}
                disabled={!me || me.trim() === ''}
              >
                Copy Your ID
              </StyledButton>
            </StyledGridItem>
            <StyledGridItem item xs={12} md={6}>
              <Typography gutterBottom variant="h6">Make a call</Typography>
              <TextField label="ID to call" value={idToCall} onChange={(e) => setIdToCall(e.target.value)} onFocus={onPasteIdToCall} fullWidth />
              {callAccepted && !callEnded ? (
                <StyledButton variant="contained" color="secondary" startIcon={<PhoneDisabled fontSize="large" />} fullWidth onClick={leaveCall}>
                  Hang Up
                </StyledButton>
              ) : (
                <StyledButton 
                  variant="contained" 
                  color="primary" 
                  disabled={!idToCall || idToCall.trim() === ''} 
                  startIcon={<Phone fontSize="large" />} 
                  fullWidth 
                  onClick={handleCall}
                >
                  Call
                </StyledButton>
              )}
            </StyledGridItem>
          </StyledGridContainer>
        </StyledForm>
        {children}
      </Paper>
      <Snackbar 
        open={showCopySnackBar} 
        autoHideDuration={5000} 
        anchorOrigin={{ vertical: 'top', horizontal: 'center' }} 
        onClose={() => setShowCopySnackBar(false)}
      >
        <Alert severity="success">
          Socket ID copied to clipboard!<br />
          <strong>{me}</strong>
        </Alert>
      </Snackbar>
      <Snackbar open={warningMessage.open} autoHideDuration={5000} anchorOrigin={{ vertical: 'top', horizontal: 'center' }} onClose={() => setWarningMessage({ message: '', open: false })}>
        <Alert severity="warning">{warningMessage.message}</Alert>
      </Snackbar>
    </Container>
  );
};

export default Sidebar;
